[colors.primary]
background = '#111418'
foreground = '#e1e2e8'

[colors.selection]
text = '#e1e2e8'
background = '#1e4876'

[colors.cursor]
text = '#111418'
cursor = '#a3c9fe'

[colors.normal]
black   = '#111418'
red     = '#ff729b'
green   = '#7ffe90'
yellow  = '#fff772'
blue    = '#89b4f1'
magenta = '#284875'
cyan    = '#a3c9fe'
white   = '#eff6ff'

[colors.bright]
black   = '#989da5'
red     = '#ff9fbb'
green   = '#a5ffb2'
yellow  = '#fffaa5'
blue    = '#b1d1ff'
magenta = '#bfd9ff'
cyan    = '#d5e7ff'
white   = '#f8fbff'
